
name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Ändere dies entsprechend der verwendeten .NET-Version

    - name: Build and pack
      run: dotnet build ExcelTabellenAuswerung.csproj --configuration Release && dotnet pack ExcelTabellenAuswerung.csproj --configuration Release --no-build

    - name: Publish to NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
      run: nuget push ExcelTabellenAuswerung.PackageId.$(Build.BuildId).nupkg --source https://api.nuget.org/v3/index.json
