name: Deploy to GitHub Releases

on:
  push:
    branches:
      - main
jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' ExcelTabellenAuswerung/ExcelTabellenAuswerung.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish Application
        run: dotnet publish ExcelTabellenAuswerung/ExcelTabellenAuswerung.csproj -c Release -o publish -r win-x64 --self-contained true
      - name: Create Velopack Release
        run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl https://github.com/jensDebernitz/EmergencyStatistic --mainExe Einsatz-Dokumentation &amp; Statistik.exe
          vpk pack -u ExcelTabellenAuswerung -v ${{ steps.get-version.outputs.version }} -p publish
          vpk upload github --repoUrl https://github.com/jensDebernitz/EmergencyStatistic --token ${{ secrets.GITHUB_TOKEN }} --publish --releaseName "EmergencyStatistic ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }}
